### PR TITLE
Upgrade to Batch SDK 1.12 + GCM -> FCM migration

### PR DESCRIPTION
**Pull request by Minishlink**

### CODE REVIEW

**Comment by mbaroukh** [comment]
Why removing setting the gcmSenderId ?

Maybe we could make it optional with something like 
```java
      int gcmSendIdResourceId = resources.getIdentifier("GCM_SENDER_ID", "string", packageName);
      if (gcmSendIdResourceId!=0) {
        Batch.Push.setGCMSenderId(resources.getString(gcmSendIdResourceId));
      }
```
So we could have choice to use either google-services.json or gcmSenderId ?

**Comment by mbaroukh** [comment]
Oups ... You removed all permissions in manifest ?

**Comment by Minishlink** [comment]
Hello @mbaroukh, this will be a major version.

Google is deprecating GCM in favor of FCM.

The permissions are now in the Batch SDK directly :)

If you still want to support GCM, you can copy the lines I deleted and add them in your project, this won't break anything.

**Comment by fshafiee** [comment]
@Minishlink, thanks for the PR.
@mbaroukh, is there an ETA when this is going to be merged? I am integrating Batch with a fresh react-native project, and I just noticed the deprecation warnings on GCM. I doesn't make much sense to use deprecated APIs now. I may be able to help testing the integration, maybe on an `unstable` branch?

**Comment by mbaroukh** [comment]
@farzadshafiee I'm not the owner of this repo :). Can't tell you.

**Comment by fshafiee** [comment]
@mbaroukh sorry, my bad. Since you responded to the PR I though it may be your decision. 😅
Seems like @Minishlink himself is in charge, so hopefully this will be merged soon?

**Comment by Minishlink** [comment]
@farzadshafiee Hello, I didn't have the time to test it, and I'm going to take this time soon but I don't know when yet. That being said, you can still use this branch in the meantime, simply replace the version by `https://github.com/bamlab/react-native-batch-push.git#6dad677a2290e3ef2bb5b5329b74b06f2ca0a8ac` in your `package.json` (it's safer targeting the commit rather than the branch)

**Comment by fshafiee** [comment]
Many thanks @Minishlink. I'll give it a try and let you know if there were any issues.

**Comment by fshafiee** [comment]
@Minishlink, it works fine. No issues so far.

**Comment by Minishlink** [comment]
Thanks for the feedback @farzadshafiee!

**Pull request merged**
