### PR TITLE
feat: Update android documentation about dependencies

### PR DESCRIPTION
**Pull request by nardor2**
`firebase-BoM` can handle other firebase dependencies versions by itself.

See https://firebase.google.com/docs/android/learn-more#bom

### CODE REVIEW

**Comment by jasondibenedetto** [comment]
@Giregm any update on getting this one merged

**Comment by nardor2** [comment]
@jasondibenedetto  
I don't think of anything else to add.
But it would be nice if someone could test with these updates

**Comment by jasondibenedetto** [comment]
@Giregm Have tested this in my build, all running as expected.

**Comment by nardor2** [comment]
@jasondibenedetto Thanks a lot for taking the time to peer-test ! 
 I'll be happy to merge on your "GO"

**Review by jasondibenedetto — APPROVED** [review]

**Pull request merged**
